### ISSUE TITLE
Travis PR integration broken

### ISSUE THREAD

**Issue by lpinca** [microapps/Nodify-Shopify#49] opened 2015-11-18 07:23 UTC
It seems that there is an issue with the Travis integration in the latest PRs.
Travis still [runs](https://travis-ci.org/microapps/Nodify-Shopify/pull_requests) but the build is not visible inline in the PRs (#46, #47, #48).

I wonder if this happened when the repository has been renamed.

**Comment by Alua-Kinzhebayeva** [comment] 2015-11-18 07:25
I guess the problem is related to renaming of the repository.

**Comment by Alua-Kinzhebayeva** [comment] 2015-11-18 07:26
+ it is missing some info for publishing npmjs

**Comment by lpinca** [comment] 2015-11-18 07:27
> It is missing some info for publishing npmjs

That's another issue.

**Comment by lpinca** [comment] 2015-11-18 07:32
@Alua-Kinzhebayeva can you try to sync the repositories on Travis and disable / reenable Nodify-Shopify?

**Comment by Alua-Kinzhebayeva** [comment] 2015-11-18 07:36
That is my plan

**Comment by Alua-Kinzhebayeva** [comment] 2015-11-18 07:52
closing this issue due to being fixed in PR #51. the problem was with the Travis variable was not being set. https://gyazo.com/3e594dc7cf5116045011c1c4bd0946f4

**Closed by Alua-Kinzhebayeva** 2015-11-18 07:52 UTC

**Comment by lpinca** [comment] 2015-11-18 08:29
Perfect, thank you.
